### ISSUE TITLE
谢谢兄弟，搜到你的ea8500固件，各个功能完美，点赞

### ISSUE THREAD

**Issue by yujunge12311** [maximaqiu/ea8500#1]

**Comment by maximaqiu** [comment]
兄弟你是认真的吗？我自己都还没有测试你就已经很稳啦？

**Comment by yujunge12311** [comment]
我自己用的Pandorabox，刷进去另一个分区试了下。这两天用过几天，只出现一个问题：给主机开加速器，主机连不上加速器分享出来的网络。另外，openwrt信号是个老大难问题，不过最近好像linux底层加了驱动，也不知道真假。

**Comment by maximaqiu** [comment]
> 我自己用的Pandorabox，刷进去另一个分区试了下。这两天用过几天，只出现一个问题：给主机开加速器，主机连不上加速器分享出来的网络。另外，openwrt信号是个老大难问题，不过最近好像linux底层加了驱动，也不知道真假。

还好。。测试了一下移动300M，跑到460M。。忘记了一个驱动没加进去。。哈 哈

**Comment by yujunge12311** [comment]
> 

哎，还是太折腾了，fork下加了个插件，结果固件刷不进路由。期待大佬给留个固件了。

**Comment by yujunge12311** [comment]
> 

哎，还是太折腾了，fork下加了个插件，结果固件刷不进路由。期待大佬给留个固件了。

**Comment by maximaqiu** [comment]
这路由挺坑的，128ROM，分了两个区，实际上超过28M的固件就刷不进去了。。插件多少少都不行。。
